version: '3'
services:
  web:
    build:
      context: ./PHP
    ports:
      - "80:80"
    volumes:
      - "./PHP/content/:/var/www/html/"
      
  database:
    build:
      context: ./SQL
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=cueh
      - MYSQL_DATABASE=maindb
